version: '3.8'
services:
  next:
    build:
      context: ./app/next                   # Build từ thư mục chứa source code
      dockerfile: ../../docker/next/Dockerfile # Dùng Dockerfile nằm bên ngoài
    ports:
      - "3000:3000"                    # Mở port cho web
    volumes:
      - ./app/next:/app                     # Mount mã nguồn để hot reload
      - /app/node_modules              # Tránh xung đột node_modules giữa host và container
    working_dir: /app
    command: sh -c "npm install && npm run dev"
