#version: '3.8'
services:
  next:
    build:
      context: ./app/next
      dockerfile: ../../docker/next/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./app/next:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    depends_on:
      - nest
  nest:
    build:
      context: ./app/nest
      dockerfile: ../../docker/nest/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./app/nest:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo
  mongo:
    image: mongo:5.0.15
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
